### ISSUE TITLE
Oracle DB connect via Oracle Internet Directory (LDAP) failed

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-samples#19]
Operator doens't support Oracle OID connection style. 

OID fails due to bad split in \OperatorCopy\common\tasks\fncm\fncm-oracle-verify.yml
```yaml
- name: set oracle value
      set_fact:
        ORACLE_INFO: "{{ datasource_configuration.dc_icn_datasource.dc_oracle_icn_jdbc_url.split('@//')[1] }}"
```

This fails: 
"jdbc:oracle:thin:**@ldap**://oid.myorg.com:3080/FNOS1,cn=OracleContext,dc=abc,dc=myorg,dc=net"

This works: 
"jdbc:oracle:thin:@//ecmOracle1.fyre.ibm.com:1521/orcl" 
#oracle host value + oracle port value + oracle sid value
